module media_multitool {
    requires javafx.controls;
    requires javafx.fxml;

    requires java.desktop;
    requires image4j;
    requires org.slf4j;
    requires javafx.swing;
    requires jave.core;
    requires net.coobird.thumbnailator;
    requires org.apache.commons.io;
    requires java.prefs;
    requires colorpicker;
    requires jaudiotagger;
    requires java.logging;
    requires org.apache.pdfbox;
    requires static lombok;
    requires ch.qos.logback.classic;
    requires ch.qos.logback.core;

    opens media_multitool to javafx.fxml;
    exports model.converterImage;
    exports model.converterVideo;
    exports model.compressorImage;
    exports media_multitool;
    exports model.utility;
    exports model.properties;
    exports model.select;
    exports model.preprocessing;
    exports viewHelp;
    exports model.enums;
    exports viewHelp.audioEditor;
    exports app;
    opens app to javafx.fxml;
    exports media_multitool.imageTools;
    opens media_multitool.imageTools to javafx.fxml;
    exports media_multitool.converters;
    opens media_multitool.converters to javafx.fxml;
    exports media_multitool.compressors;
    opens media_multitool.compressors to javafx.fxml;
    exports media_multitool.editors;
    opens media_multitool.editors to javafx.fxml;
    exports media_multitool.pdf;
    opens media_multitool.pdf to javafx.fxml;
    exports model.checks;
    exports media_multitool.watermarks;
    opens media_multitool.watermarks to javafx.fxml;
    exports model.helper.watermarks;
    opens model.helper.watermarks to javafx.fxml;
    exports media_multitool.watermarks.viewController;
    opens media_multitool.watermarks.viewController to javafx.fxml;
}